#!/usr/bin/env python3
import ast,hashlib,json,os,stat,subprocess,sys
from pathlib import Path
AUTHORITY_ID="PM-D2-R7B-I1-R34-COLLECTOR-ONLY-ACTIVATION-260729-2034"; ROOT=Path("/Users/chenjie/Documents/MES/edge-mes-demo"); E=ROOT/"docs/reports/evidence/d2_r7b_i1_r34_collector_only_activation"; RUN=E/"run_activation.py"; CTL=E/"remote_activation_controller.py"; LOCAL=E/"local_prerequisite_terminal.json"; REMOTE=E/"activation_terminal.json"; REPORT=ROOT/"docs/reports/sprint4_d2_r7b_i1_r34_collector_only_activation.md"; MAN=E/"manifest.sha256"; KEY=Path("/Users/chenjie/.ssh/edge_pi_codex")
R33E=ROOT/"docs/reports/evidence/d2_r7b_i1_r33_fresh_readonly_remote_activation_preflight"; R33=ROOT/"docs/reports/sprint4_d2_r7b_i1_r33_fresh_readonly_remote_activation_preflight.md"
DIRTY=[".gitignore","docs/reports/evidence/d2_r7b_p2_r2/local_materialization.sh","docs/reports/evidence/d2_r7b_p2_r2/manifest.sha256","docs/reports/evidence/d2_r7b_p2_r3/manifest.sha256","docs/reports/evidence/d2_r7b_p2_r3/remote_i1_orchestrator.py","docs/thread_handoff/pm_operating_rules.md"]
IDS={"docs/reports/sprint4_d2_r7b_i1_r31_package_closed_collector_image_materialization_deployment_plan.md":(45360,"bd5b65ac08dcacfd0fc14a639626d807f28d429f1038a99aa124cd6ce85db894"),"docs/reports/sprint4_d2_r7b_i1_r33_fresh_readonly_remote_activation_preflight.md":(6049,"daa0af5824d697ad12342fcaedf09330b082da78475f1351fec46c0892153c66"),"docs/reports/evidence/d2_r7b_i1_r33_fresh_readonly_remote_activation_preflight/run_readonly_preflight.py":(11422,"3f3c34c0157b8fedc1a30acb0561c04203d390710a601a70dd9c0dc6cdc8bf97"),"docs/reports/evidence/d2_r7b_i1_r33_fresh_readonly_remote_activation_preflight/remote_readonly_probe.py":(14245,"9223c4cd7b63072a39936029681ee0b4b007e58838bba0626d4515d9e47a6430),"docs/reports/evidence/d2_r7b_i1_r33_fresh_readonly_remote_activation_preflight/local_prerequisite_terminal.json":(7796,"2c0b342168195de98bd0dbda627a5e3231f2dd54cac57fcea850596449fa87de"),"docs/reports/evidence/d2_r7b_i1_r33_fresh_readonly_remote_activation_preflight/remote_preflight_terminal.json":(50786,"d1cd628fdf6ffacf62c5ceb1e418284bf4663ac5d9642cfdeead51eec423a82e"),"docs/reports/evidence/d2_r7b_i1_r33_fresh_readonly_remote_activation_preflight/manifest.sha256":(842,"5c52278d1a8585d8c19402546a2dd231f58f717ba6ef97e756ee19a9729bbaad),"docker-compose.yml":(5698,"c10dc292bce971ce857051e36268a3be9e9377e63d5e3cd58d2514e3e824ed66),"config/mapping.yaml":(7112,"d9bb5fcb017e6ab491e8643077c793bb018011d1cbe0698172e4c08823080c9d)}
def h(p): b=p.read_bytes();s=os.lstat(p);return {"path":str(p.relative_to(ROOT)),"bytes":len(b),"sha256":hashlib.sha256(b).hexdigest(),"regular":stat.S_ISREG(s.st_mode),"symlink":stat.S_ISLNK(s.st_mode)}
def g(*a):p=subprocess.run(["git",*a],cwd=ROOT,stdout=subprocess.PIPE,stderr=subprocess.PIPE,check=False);return p.returncode,p.stdout.decode("utf-8","strict").strip(),p.stderr.decode("utf-8","strict").strip()
def write(p,x):p.write_text(json.dumps(x,sort_keys=True,indent=2)+"\n",encoding="utf-8")
def controller_snapshot():
 t=ast.parse(CTL.read_text(encoding="utf-8"),str(CTL))
 for n in t.body:
  if isinstance(n,ast.Assign) and any(isinstance(q,ast.Name) and q.id=="EXPECTED_SNAPSHOT_B" for q in n.targets):
   return json.loads(ast.literal_eval(n.value.args[0]))
 raise ValueError("embedded prestate missing")
def manifest():
 paths=[REPORT,RUN,CTL,LOCAL,REMOTE]; MAN.write_text("".join(f"{hashlib.sha256(p.read_bytes()).hexdigest()}  {p.relative_to(ROOT)}\n" for p in paths),encoding="utf-8");return all(len(x.split())==2 and hashlib.sha256((ROOT/x.split()[1]).read_bytes()).hexdigest()==x.split()[0] for x in MAN.read_text().splitlines())
def report(local,remote):
 txt=f"""# Sprint 4 D2-R7B-I1 R34 Collector-Only Activation Execution\n\n- 结论：{local["status"]}\n- Terminal classification：{local["classification"]}\n- Authority：{AUTHORITY_ID}\n- R33：identity and manifest 5/5 verified; terminal PASS / ACTIVATION_ELIGIBLE.\n- Remote-call audit：structured SSH {local["ssh_capture"]["calls"]}; retry/resume/supplemental 0.\n- Mutation audit：{remote.get("mutation_audit",{})}\n- Evidence boundary：Phase 4 receipt only; ACTIVATED、RUNTIME-LOADED、PRODUCTION-ACCEPTED are not established.\n- Allowlist：exact six R34 outputs only; Git stage/commit/push none.\n- MVP 路径一致性：MVP-ALIGNED; minimum invariant is exact alias mutation plus Collector-only recreation without protected-service/config drift.\n- Next gate：ChatGPT PM durable intake only.\n""";REPORT.write_text(txt,encoding="utf-8")
def main():
 facts={k:g(*v) for k,v in {"root":("rev-parse","--show-toplevel"),"branch":("rev-parse","--abbrev-ref","HEAD"),"head":("rev-parse","HEAD"),"origin":("rev-parse","origin/main"),"parent":("rev-parse","HEAD^"),"ahead":("rev-list","--left-right","--count","HEAD...origin/main"),"dirty":("diff","--name-only"),"cached":("diff","--cached","--name-only"),"check":("diff","--check"),"cached_check":("diff","--cached","--check")}.items()}
 assertions={"baseline":facts["root"][1]==str(ROOT) and facts["branch"][1]=="main" and facts["head"][1]==facts["origin"][1]=="ac33e6bae449ecdd9b77a53daaf7271f14133000" and facts["parent"][1]=="66563677d3d1129fbc79c2c284b5f6d8b62f1932" and facts["ahead"][1]=="0\t0","tracked_dirty":facts["dirty"][1].splitlines()==DIRTY,"index_empty":facts["cached"][1]=="","diff_checks":facts["check"][0]==facts["cached_check"][0]==0 and not facts["check"][1] and not facts["cached_check"][1],"mapping_clean":g("diff","--quiet","HEAD","--","config/mapping.yaml")[0]==0}
 identities={x:h(ROOT/x) for x in IDS};assertions["identities"]=all(v["regular"] and not v["symlink"] and (v["bytes"],v["sha256"])==IDS[k] for k,v in identities.items())
 r33man=subprocess.run(["shasum","-a","256","-c",str(R33E/"manifest.sha256")],cwd=ROOT,stdout=subprocess.PIPE,stderr=subprocess.PIPE);assertions["r33_manifest"]=r33man.returncode==0 and r33man.stdout.count(b": OK")==5
 r33local=json.loads((R33E/"local_prerequisite_terminal.json").read_text());r33remote=json.loads((R33E/"remote_preflight_terminal.json").read_text());assertions["r33_gate"]=r33local.get("status")=="PASS" and r33local.get("classification")=="ACTIVATION_ELIGIBLE" and r33remote.get("status")=="PASS"
 key=os.lstat(KEY);assertions["key"]=stat.S_ISREG(key.st_mode) and not stat.S_ISLNK(key.st_mode) and key.st_uid==501 and stat.S_IMODE(key.st_mode)==0o600
 before={"runner":h(RUN),"controller":h(CTL)}
 try: ast.parse(RUN.read_text(),str(RUN));ast.parse(CTL.read_text(),str(CTL));assertions["syntax"]=True
 except Exception:assertions["syntax"]=False
 try: assertions["embedded_prestate"]=controller_snapshot()==r33remote["observed"]["snapshot_b"]
 except Exception:assertions["embedded_prestate"]=False
 local={"schema_version":"d2-r7b-i1-r34-local/v1","authority_id":AUTHORITY_ID,"git":facts,"identities":identities,"assertions":assertions,"helpers_preliminary":before,"remote_call_budget":{"structured_ssh_calls":0,"retry":0,"resume":0,"supplemental_ssh":0},"ssh_capture":{"calls":0,"returncode":None,"stdout_bytes":0,"stderr_bytes":0},"local_mutation_audit":{"git":0,"docker":0,"cleanup":0}}
 if not all(assertions.values()):
  remote={"schema_version":"d2-r7b-i1-r34-remote-activation/v1","authority_id":AUTHORITY_ID,"status":"HOLD","classification":"REMOTE_NOT_OBSERVED","phase_history":[],"observed":{},"assertions":{},"command_audit":[],"mutation_audit":{"tag_mutation_count":0,"compose_recreate_count":0,"collector_lifecycle_count":0,"protected_service_lifecycle_count":0,"rollback_count":0,"cleanup_count":0},"remote_call_budget":{"structured_ssh_calls":0,"retry":0,"resume":0,"supplemental_ssh":0}};local.update(status="HOLD",classification="LOCAL_PREREQUISITE_FAILED")
 else:
  ssh=["ssh","-T","-p","22","-o","BatchMode=yes","-o","IdentitiesOnly=yes","-i",str(KEY),"-o","ControlMaster=no","-o","ControlPersist=no","-o","ForwardAgent=no","-o","StrictHostKeyChecking=yes","-o","ConnectTimeout=10","-o","ServerAliveInterval=5","-o","ServerAliveCountMax=2","-o","LogLevel=ERROR","mari@10.0.0.217","/usr/bin/python3","-"];p=subprocess.run(ssh,input=CTL.read_bytes(),stdout=subprocess.PIPE,stderr=subprocess.PIPE,check=False);local["remote_call_budget"]["structured_ssh_calls"]=1;local["ssh_capture"]={"calls":1,"returncode":p.returncode,"stdout_bytes":len(p.stdout),"stderr_bytes":len(p.stderr),"stdout_sha256":hashlib.sha256(p.stdout).hexdigest(),"stderr_sha256":hashlib.sha256(p.stderr).hexdigest()}
  try: remote=json.loads(p.stdout.decode("utf-8","strict"))
  except Exception:remote=None
  required={"schema_version","authority_id","status","classification","phase_history","observed","assertions","command_audit","mutation_audit","remote_call_budget"}
  valid=isinstance(remote,dict) and required<=set(remote) and remote["authority_id"]==AUTHORITY_ID and len(remote["command_audit"])<=12 and remote["mutation_audit"].get("tag_mutation_count") in (0,1) and remote["mutation_audit"].get("compose_recreate_count") in (0,1)
  if p.returncode!=0 or p.stderr or not valid: remote={"schema_version":"d2-r7b-i1-r34-remote-activation/v1","authority_id":AUTHORITY_ID,"status":"HOLD","classification":"REMOTE_STATE_MAY_BE_AMBIGUOUS","phase_history":[],"observed":{},"assertions":{},"command_audit":[],"mutation_audit":{"tag_mutation_count":0,"compose_recreate_count":0,"collector_lifecycle_count":0,"protected_service_lifecycle_count":0,"rollback_count":0,"cleanup_count":0},"remote_call_budget":{"structured_ssh_calls":1,"retry":0,"resume":0,"supplemental_ssh":0}}
  local.update(status="PASS" if valid and p.returncode==0 and not p.stderr and remote["status"]=="PASS" else "HOLD",classification=remote["classification"])
 local["helpers_final"]={"runner":h(RUN),"controller":h(CTL)};local["assertions"]["helpers_unchanged"]=local["helpers_preliminary"]==local["helpers_final"];write(LOCAL,local);write(REMOTE,remote);report(local,remote);local["manifest_5_5"]=manifest();write(LOCAL,local);manifest();print(json.dumps({"status":local["status"],"classification":local["classification"]}))
if __name__=="__main__":main()

