apiVersion: 1

datasources:
  - name: Edge MES Prometheus
    type: prometheus
    uid: edge-mes-prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    editable: true
    jsonData:
      timeInterval: 10s
