"""Flexible line configuration loading and validation."""

from .loader import LineConfigError, load_line_config
from .deployment import (
    PlcDeploymentCandidate,
    candidate_content_hash,
    candidate_to_dict,
    parse_deployment_candidate,
)
from .debug_contract import (
    CONFIRMATION_STATES,
    WRITE_MODE,
    DebugContractError,
    debug_candidate_content_hash,
    debug_candidate_to_dict,
    debug_contract_content_hash,
    debug_contract_from_candidate,
    debug_contract_from_mapping,
    debug_contract_to_dict,
    engineering_export,
    engineering_rows,
    normalize_debug_candidate,
    parse_debug_candidate,
)
from .models import (
    BufferConfig,
    CycleProfile,
    DbMapping,
    HardwareEnvelope,
    LineConfig,
    LoadEstimate,
    NokCode,
    NokTemplate,
    PayloadField,
    PayloadTemplate,
    PlcConfig,
    RouteEdge,
    RouteGraph,
    ScenarioConfig,
    SimulationTiming,
    StationConfig,
)
from .resolver import (
    canonicalize_config,
    compute_config_hash,
    estimate_config_load,
    resolve_line_config,
)
from .runtime_layout import RuntimeLayoutRegistry, default_runtime_layout_registry
from .runtime_projection import (
    RuntimeMappingProjection,
    RuntimeProjectionError,
    compile_runtime_mapping,
)
from .validator import validate_line_config

__all__ = [
    "BufferConfig",
    "CONFIRMATION_STATES",
    "PlcDeploymentCandidate",
    "CycleProfile",
    "DbMapping",
    "HardwareEnvelope",
    "LineConfig",
    "LineConfigError",
    "LoadEstimate",
    "NokCode",
    "NokTemplate",
    "PayloadField",
    "PayloadTemplate",
    "PlcConfig",
    "RouteEdge",
    "RouteGraph",
    "ScenarioConfig",
    "SimulationTiming",
    "StationConfig",
    "canonicalize_config",
    "candidate_content_hash",
    "candidate_to_dict",
    "compute_config_hash",
    "estimate_config_load",
    "load_line_config",
    "parse_deployment_candidate",
    "resolve_line_config",
    "RuntimeLayoutRegistry",
    "RuntimeMappingProjection",
    "RuntimeProjectionError",
    "WRITE_MODE",
    "DebugContractError",
    "compile_runtime_mapping",
    "default_runtime_layout_registry",
    "debug_candidate_content_hash",
    "debug_candidate_to_dict",
    "debug_contract_content_hash",
    "debug_contract_from_candidate",
    "debug_contract_from_mapping",
    "debug_contract_to_dict",
    "engineering_export",
    "engineering_rows",
    "normalize_debug_candidate",
    "parse_debug_candidate",
    "validate_line_config",
]
